apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
spec:
  selector:
    matchLabels:
      app:  {{SERVICE_NAME}}-template
  template:
    metadata:
      labels:
        app:  {{SERVICE_NAME}}-template
    spec:
      containers:
      - name: {{SERVICE_NAME}}
        image: {{CASITA_IMAGE_NAME_TAG}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {{#if COMMAND}}
        command: ["{{{COMMAND}}}"]
        {{/if}}
        {{#if ARGS}}
        args: {{{json ARGS}}}
        {{/if}}
        env:
        - name: INSTANCE_ENV
          value: "{{BRANCH}}"
        {{#each env}}
        - name: {{name}}
          value: "{{value}}"
        {{/each}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        envFrom:
        - secretRef:
            name: local-dev-secrets
        volumeMounts:
        - mountPath: /storage/network
          name: nfspsc
        - name: local-casita-tasks
          mountPath: /casita/tasks
          readOnly: true
        - name: local-casita-node-commons
          mountPath: /casita/node-commons
          readOnly: true
        - name: local-casita-services
          mountPath: /casita/services
          readOnly: true
        {{#each volumes}}
        - name: {{name}}
          mountPath: {{mountPath}}
        {{/each}}
      volumes:
      {{#each volumes}}
      - name: {{name}}
        hostPath:
          path: /hosthome/{{../HOME_HOST_PATH}}/{{hostPath}}
          {{#if type}}
          type: {{type}}
          {{/if}}
      {{/each}}
      - name: local-casita-tasks
        hostPath:
          path: /hosthome/{{HOME_HOST_PATH}}/{{CASITA_TASKS_REPO_NAME}}/tasks
      - name: local-casita-node-commons
        hostPath:
          path: /hosthome/{{HOME_HOST_PATH}}/{{CASITA_TASKS_REPO_NAME}}/node-commons
      - name: local-casita-services
        hostPath:
          path: /hosthome/{{HOME_HOST_PATH}}/{{CASITA_TASKS_REPO_NAME}}/services
      - name: nfspsc
        persistentVolumeClaim:
          claimName: {{pvc-name}}
          readOnly: false
      {{#if nodeSelector}}
      nodeSelector:
        {{#if intendedfor}}
        intendedfor: {{intendedfor}}
        {{/if}}
      {{/if}}
{{OK}}